ERROR_SPECIFICATION_FILE = -1
ERROR_MARKET_DATA_FILE = -2
ERROR_PARAMS_FILE = -3

OBJ_MIN_COST = 1
OBJ_CONGESTION_MANAGEMENT = 2

BRANCH_LIMIT_CURRENT = 1
BRANCH_LIMIT_APPARENT_POWER = 2
BRANCH_LIMIT_MIXED = 3