ERROR_SPECIFICATION_FILE = -1
ERROR_MARKET_DATA_FILE = -2
ERROR_PARAMS_FILE = -3
ERROR_NETWORK_FILE = -4
ERROR_OPERATIONAL_DATA_FILE = -5

BUS_PQ = 1
BUS_PV = 2
BUS_REF = 3
BUS_ISOLATED = 4

OBJ_MIN_COST = 1
OBJ_CONGESTION_MANAGEMENT = 2

BRANCH_LIMIT_CURRENT = 1
BRANCH_LIMIT_APPARENT_POWER = 2
BRANCH_LIMIT_MIXED = 3

GEN_REFERENCE = 0
GEN_CONV = 1
GEN_RES_WIND = 2
GEN_RES_SOLAR = 3
GEN_RES_OTHER = 4
GEN_RES_CONTROLLABLE = 5
GEN_CONTROLLABLE_TYPES = [GEN_REFERENCE, GEN_CONV, GEN_RES_CONTROLLABLE]
GEN_CURTAILLABLE_TYPES = [GEN_RES_WIND, GEN_RES_SOLAR, GEN_RES_OTHER]
GEN_RENEWABLE_TYPES = [GEN_RES_WIND, GEN_RES_SOLAR, GEN_RES_OTHER, GEN_RES_CONTROLLABLE]

ENERGY_STORAGE_MAX_ENERGY_STORED = 0.95
ENERGY_STORAGE_MIN_ENERGY_STORED = 0.05
ENERGY_STORAGE_RELATIVE_INIT_SOC = 0.50

DATA_ACTIVE_POWER = 1
DATA_REACTIVE_POWER = 2
DATA_UPWARD_FLEXIBILITY = 3
DATA_DOWNWARD_FLEXIBILITY = 4
DATA_COST_FLEXIBILITY = 5
